PROC SQL;
    CREATE TABLE THER AS
    SELECT a.D_AGEGRP,
		   b.DER_DUR
    FROM Afinal23.demo23_d AS a
    INNER JOIN Afinal23.THER23_d AS b
        ON a.PRIMARYI = b.PRIMARYI
       AND a.CASEID   = b.CASEID
	WHERE a.D_AGEGRP NE "MISSIN"
    ;
QUIT;

PROC MEANS Data=THER;
	CLASS D_AGEGRP;
	VAR DER_DUR;
	OUTPUT OUT= DSTATS (DROP=_TYPE_ _FREQ_) 
	N=_N
	MEAN=_MEAN
	STD=_STD
	MEDIAN=_MEDIAN
	MIN=_MIN
	MAX=_MAX;
RUN;

DATA DSTATS1;
	LENGTH N MEAN MEDIAN GM MIN MAX STD RANGE $40.;
	set DSTATS;

	IF D_AGEGRP = '' THEN D_AGEGRP = 'TOTAL';

	N=COMPRESS(PUT(_N,10.));
	MEAN=COMPRESS(PUT(_MEAN,10.2));
	MEDIAN=COMPRESS(PUT(_MEDIAN,10.2));
	GM=COMPRESS(PUT(GEOMEAN(_MEAN),10.2));
	MIN=COMPRESS(PUT(_MIN,10.2));
	MAX=COMPRESS(PUT(_MAX,10.2));
	STD=COMPRESS(PUT(_STD,10.2));
	RANGE=COMPRESS(CATX("-",_MIN,_MAX));
RUN;

PROC SORT Data=DSTATS1 Out=DSTATS2;
	BY D_AGEGRP;
RUN;

PROC TRANSPOSE Data=DSTATS2 Out=THER_final (DROP=_LABEL_);
	ID D_AGEGRP;
	VAR N MEAN MEDIAN GM MIN MAX STD RANGE;
RUN;
